spring:
  config:
    activate:
      on-profile: qa

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  datasource:
    url: jdbc:mysql://localhost:3306/bookride
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: